JSONResponse = [
  {
	"country" : "AE",
	"country_name" : "ОАЭ",
	"special" : "",
	"providers" : [{
	"code" : "du",
	"name" : "DU",
	"number" : "2420",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 2.72,
	"profit" : 30,
	"vat" : 0,
	"currency" : "AED",
	"special" : ""
},{
	"code" : "etisalat",
	"name" : "Etisalat",
	"number" : "2252",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 2.72,
	"profit" : 30,
	"vat" : 0,
	"currency" : "AED",
	"special" : ""
}]
},{
	"country" : "AL",
	"country_name" : "Албания",
	"number" : "51115",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 120.00,
	"usd" : 0.96,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "ALL",
	"special" : "",
	"providers" : []
},{
	"country" : "AM",
	"country_name" : "Армения",
	"number" : "3024",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 480.00,
	"usd" : 1.1,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "AMD",
	"special" : "",
	"providers" : []
},{
	"country" : "AM",
	"country_name" : "Армения",
	"number" : "5025",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1200.00,
	"usd" : 2.75,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "AMD",
	"special" : "",
	"providers" : []
},{
	"country" : "AM",
	"country_name" : "Армения",
	"number" : "5026",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2000.00,
	"usd" : 4.58,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "AMD",
	"special" : "",
	"providers" : []
},{
	"country" : "AT",
	"country_name" : "Австрия",
	"number" : "0901050110",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.50,
	"usd" : 0.55,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "AT",
	"country_name" : "Австрия",
	"number" : "0900242240",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.99,
	"usd" : 2.16,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "AT",
	"country_name" : "Австрия",
	"number" : "0930400880",
	"prefix" : "530",
	"rewrite" : "",
	"price" : 2.99,
	"usd" : 3.23,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "AT",
	"country_name" : "Австрия",
	"number" : "0930400880",
	"prefix" : "550",
	"rewrite" : "",
	"price" : 4.99,
	"usd" : 5.4,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "AZ",
	"country_name" : "Азербайджан",
	"special" : "",
	"providers" : [{
	"code" : "azercell",
	"name" : "Azercell",
	"number" : "9525",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 5.22,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
},{
	"code" : "azercell",
	"name" : "Azercell",
	"number" : "8797",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 1.04,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
},{
	"code" : "azerfon",
	"name" : "Nar Mobile",
	"number" : "3304",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 5.22,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
},{
	"code" : "azerfon",
	"name" : "Nar Mobile",
	"number" : "3302",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.99,
	"usd" : 2.08,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
},{
	"code" : "azerfon",
	"name" : "Nar Mobile",
	"number" : "3301",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.75,
	"usd" : 0.77,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
},{
	"code" : "bakcell",
	"name" : "Bakcell",
	"number" : "3304",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 5.22,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
},{
	"code" : "bakcell",
	"name" : "Bakcell",
	"number" : "3302",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 2.08,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
},{
	"code" : "bakcell",
	"name" : "Bakcell",
	"number" : "3301",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.90,
	"usd" : 0.93,
	"profit" : 27,
	"vat" : 1,
	"currency" : "AZN",
	"special" : ""
}]
},{
	"country" : "BE",
	"country_name" : "Бельгия",
	"number" : "7233",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 2.14,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "BE",
	"country_name" : "Бельгия",
	"number" : "3907",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 3.22,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "BE",
	"country_name" : "Бельгия",
	"number" : "7997",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.00,
	"usd" : 4.3,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "BG",
	"country_name" : "Болгария",
	"number" : "1855",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.60,
	"usd" : 0.33,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "BGN",
	"special" : "",
	"providers" : []
},{
	"country" : "BG",
	"country_name" : "Болгария",
	"number" : "1915",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.20,
	"usd" : 0.67,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "BGN",
	"special" : "",
	"providers" : []
},{
	"country" : "BG",
	"country_name" : "Болгария",
	"number" : "1935",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.40,
	"usd" : 1.33,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "BGN",
	"special" : "",
	"providers" : []
},{
	"country" : "BG",
	"country_name" : "Болгария",
	"number" : "1978",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.80,
	"usd" : 2.67,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "BGN",
	"special" : "",
	"providers" : []
},{
	"country" : "BG",
	"country_name" : "Болгария",
	"number" : "1983",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 6.00,
	"usd" : 3.33,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "BGN",
	"special" : "",
	"providers" : []
},{
	"country" : "BY",
	"country_name" : "Белоруссия",
	"number" : "3338",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2500.00,
	"usd" : 0.83,
	"profit" : 25.00,
	"vat" : 0,
	"currency" : "BYR",
	"special" : "",
	"providers" : []
},{
	"country" : "BY",
	"country_name" : "Белоруссия",
	"number" : "3337",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5900.00,
	"usd" : 1.95,
	"profit" : 25.00,
	"vat" : 0,
	"currency" : "BYR",
	"special" : "",
	"providers" : []
},{
	"country" : "BY",
	"country_name" : "Белоруссия",
	"number" : "3336",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9900.00,
	"usd" : 3.27,
	"profit" : 25.00,
	"vat" : 0,
	"currency" : "BYR",
	"special" : "",
	"providers" : []
},{
	"country" : "CH",
	"country_name" : "Швейцария",
	"number" : "543",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 0.50,
	"usd" : 0.46,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "CHF",
	"special" : "",
	"providers" : []
},{
	"country" : "CH",
	"country_name" : "Швейцария",
	"number" : "543",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 0.92,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "CHF",
	"special" : "",
	"providers" : []
},{
	"country" : "CH",
	"country_name" : "Швейцария",
	"number" : "543",
	"prefix" : "520",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 1.84,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "CHF",
	"special" : "",
	"providers" : []
},{
	"country" : "CH",
	"country_name" : "Швейцария",
	"number" : "543",
	"prefix" : "530",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 2.76,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "CHF",
	"special" : "",
	"providers" : []
},{
	"country" : "CH",
	"country_name" : "Швейцария",
	"number" : "543",
	"prefix" : "550",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 4.6,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "CHF",
	"special" : "",
	"providers" : []
},{
	"country" : "CY",
	"country_name" : "Кипр",
	"number" : "7500",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.93,
	"usd" : 4.44,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "Сотовый оператор: &lt;b&gt;Cyta&lt;/b&gt;",
	"providers" : []
},{
	"country" : "CZ",
	"country_name" : "Чехия",
	"number" : "9033320",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 20.00,
	"usd" : 0.88,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "CZK",
	"special" : "",
	"providers" : []
},{
	"country" : "CZ",
	"country_name" : "Чехия",
	"number" : "9033350",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 50.00,
	"usd" : 2.2,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "CZK",
	"special" : "",
	"providers" : []
},{
	"country" : "CZ",
	"country_name" : "Чехия",
	"number" : "9033399",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 99.00,
	"usd" : 4.37,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "CZK",
	"special" : "",
	"providers" : []
},{
	"country" : "DE",
	"country_name" : "Германия",
	"number" : "66777",
	"prefix" : "501",
	"rewrite" : "",
	"price" : 0.99,
	"usd" : 1.08,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "DE",
	"country_name" : "Германия",
	"number" : "66777",
	"prefix" : "502",
	"rewrite" : "",
	"price" : 1.99,
	"usd" : 2.17,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "DE",
	"country_name" : "Германия",
	"number" : "66777",
	"prefix" : "503",
	"rewrite" : "",
	"price" : 2.99,
	"usd" : 3.26,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "DE",
	"country_name" : "Германия",
	"number" : "66777",
	"prefix" : "504",
	"rewrite" : "",
	"price" : 3.99,
	"usd" : 4.35,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "DE",
	"country_name" : "Германия",
	"number" : "66777",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 4.99,
	"usd" : 5.44,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "DE",
	"country_name" : "Германия",
	"number" : "66777",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 9.99,
	"usd" : 10.91,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "DK",
	"country_name" : "Дания",
	"number" : "1273",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 0.7,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "DKK",
	"special" : "",
	"providers" : []
},{
	"country" : "DK",
	"country_name" : "Дания",
	"number" : "1273",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 1.4,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "DKK",
	"special" : "",
	"providers" : []
},{
	"country" : "DK",
	"country_name" : "Дания",
	"number" : "1273",
	"prefix" : "515",
	"rewrite" : "",
	"price" : 15.00,
	"usd" : 2.11,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "DKK",
	"special" : "",
	"providers" : []
},{
	"country" : "DK",
	"country_name" : "Дания",
	"number" : "1273",
	"prefix" : "520",
	"rewrite" : "",
	"price" : 20.00,
	"usd" : 2.81,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "DKK",
	"special" : "",
	"providers" : []
},{
	"country" : "DK",
	"country_name" : "Дания",
	"number" : "1273",
	"prefix" : "530",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 4.21,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "DKK",
	"special" : "",
	"providers" : []
},{
	"country" : "DK",
	"country_name" : "Дания",
	"number" : "1230",
	"prefix" : "550",
	"rewrite" : "",
	"price" : 50.00,
	"usd" : 7.02,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "DKK",
	"special" : "",
	"providers" : []
},{
	"country" : "DK",
	"country_name" : "Дания",
	"number" : "1230",
	"prefix" : "560",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 8.42,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "DKK",
	"special" : "",
	"providers" : []
},{
	"country" : "EE",
	"country_name" : "Эстония",
	"number" : "1311",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 0.35,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "EEK",
	"special" : "Price € 0.32 + normal network rates apply",
	"providers" : []
},{
	"country" : "EE",
	"country_name" : "Эстония",
	"number" : "13011",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 0.7,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "EEK",
	"special" : "Price € 0.64 + normal network rates apply",
	"providers" : []
},{
	"country" : "EE",
	"country_name" : "Эстония",
	"number" : "15330",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 15.00,
	"usd" : 1.04,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "EEK",
	"special" : "Price € 0.96 + normal network rates apply",
	"providers" : []
},{
	"country" : "EE",
	"country_name" : "Эстония",
	"number" : "13013",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 25.00,
	"usd" : 1.74,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "EEK",
	"special" : "Price € 1.60 + normal network rates apply",
	"providers" : []
},{
	"country" : "EE",
	"country_name" : "Эстония",
	"number" : "13015",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 39.00,
	"usd" : 2.71,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "EEK",
	"special" : "Price € 2.49 + normal network rates apply",
	"providers" : []
},{
	"country" : "EE",
	"country_name" : "Эстония",
	"number" : "13017",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 50.00,
	"usd" : 3.48,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "EEK",
	"special" : "Price € 3.20 + normal network rates apply",
	"providers" : []
},{
	"country" : "ES",
	"country_name" : "Испания",
	"number" : "27333",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.90,
	"usd" : 1.17,
	"profit" : 35.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "ES",
	"country_name" : "Испания",
	"number" : "35000",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 2.6,
	"profit" : 40.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "ES",
	"country_name" : "Испания",
	"number" : "37333",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 3.9,
	"profit" : 40.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "ES",
	"country_name" : "Испания",
	"number" : "35989",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.00,
	"usd" : 5.19,
	"profit" : 40.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "ES",
	"country_name" : "Испания",
	"number" : "37555",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 6.49,
	"profit" : 40.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "ES",
	"country_name" : "Испания",
	"number" : "35969",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 6.00,
	"usd" : 7.79,
	"profit" : 40.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FI",
	"country_name" : "Финляндия",
	"number" : "17159",
	"prefix" : "513",
	"rewrite" : "",
	"price" : 1.30,
	"usd" : 1.38,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FI",
	"country_name" : "Финляндия",
	"number" : "17159",
	"prefix" : "525",
	"rewrite" : "",
	"price" : 2.50,
	"usd" : 2.64,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FI",
	"country_name" : "Финляндия",
	"number" : "17211",
	"prefix" : "503",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 3.17,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FI",
	"country_name" : "Финляндия",
	"number" : "17211",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 5.29,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FI",
	"country_name" : "Финляндия",
	"number" : "17211",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 10.56,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FR",
	"country_name" : "Франция",
	"number" : "71004",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 0.50,
	"usd" : 0.55,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FR",
	"country_name" : "Франция",
	"number" : "81027",
	"prefix" : "515",
	"rewrite" : "",
	"price" : 1.50,
	"usd" : 1.62,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "FR",
	"country_name" : "Франция",
	"number" : "81015",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 3.26,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "GE",
	"country_name" : "Грузия",
	"number" : "8886",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 0.46,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "GEL",
	"special" : "",
	"providers" : []
},{
	"country" : "GE",
	"country_name" : "Грузия",
	"number" : "8889",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 0.92,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "GEL",
	"special" : "",
	"providers" : []
},{
	"country" : "GE",
	"country_name" : "Грузия",
	"number" : "8882",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.30,
	"usd" : 1.99,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "GEL",
	"special" : "",
	"providers" : []
},{
	"country" : "GE",
	"country_name" : "Грузия",
	"number" : "6210",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 2.32,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "GEL",
	"special" : "",
	"providers" : []
},{
	"country" : "GR",
	"country_name" : "Греция",
	"number" : "54045",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.30,
	"usd" : 0.32,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "GR",
	"country_name" : "Греция",
	"number" : "54340",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.62,
	"usd" : 0.65,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "GR",
	"country_name" : "Греция",
	"number" : "54344",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.23,
	"usd" : 1.3,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "GR",
	"country_name" : "Греция",
	"number" : "54345",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.62,
	"usd" : 3.82,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "HU",
	"country_name" : "Венгрия",
	"number" : "0691222322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 200.00,
	"usd" : 0.92,
	"profit" : 35.00,
	"vat" : 0,
	"currency" : "HUF",
	"special" : "",
	"providers" : []
},{
	"country" : "HU",
	"country_name" : "Венгрия",
	"number" : "0691227910",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 600.00,
	"usd" : 2.77,
	"profit" : 40.00,
	"vat" : 0,
	"currency" : "HUF",
	"special" : "",
	"providers" : []
},{
	"country" : "HU",
	"country_name" : "Венгрия",
	"number" : "0690619916",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1600.00,
	"usd" : 7.39,
	"profit" : 40.00,
	"vat" : 0,
	"currency" : "HUF",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "550",
	"rewrite" : "",
	"price" : 0.50,
	"usd" : 0.12,
	"profit" : 17.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "501",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 0.23,
	"profit" : 24.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "502",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 0.46,
	"profit" : 29.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "503",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 0.69,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "504",
	"rewrite" : "",
	"price" : 4.00,
	"usd" : 0.92,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 1.15,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "506",
	"rewrite" : "",
	"price" : 6.00,
	"usd" : 1.38,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "507",
	"rewrite" : "",
	"price" : 7.00,
	"usd" : 1.61,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "508",
	"rewrite" : "",
	"price" : 8.00,
	"usd" : 1.84,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 2.3,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "511",
	"rewrite" : "",
	"price" : 11.00,
	"usd" : 2.53,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "512",
	"rewrite" : "",
	"price" : 12.00,
	"usd" : 2.76,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "515",
	"rewrite" : "",
	"price" : 15.00,
	"usd" : 3.45,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "518",
	"rewrite" : "",
	"price" : 18.00,
	"usd" : 4.14,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "IL",
	"country_name" : "Израиль",
	"number" : "5111",
	"prefix" : "520",
	"rewrite" : "",
	"price" : 20.00,
	"usd" : 4.6,
	"profit" : 33.00,
	"vat" : 1,
	"currency" : "Sheqel",
	"special" : "",
	"providers" : []
},{
	"country" : "KG",
	"country_name" : "Киргизия",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 1,
	"profit" : 25.00,
	"vat" : 0,
	"currency" : "USD",
	"special" : "",
	"providers" : []
},{
	"country" : "KG",
	"country_name" : "Киргизия",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 3,
	"profit" : 25.00,
	"vat" : 0,
	"currency" : "USD",
	"special" : "",
	"providers" : []
},{
	"country" : "KZ",
	"country_name" : "Казахстан",
	"special" : "",
	"providers" : [{
	"code" : "altel",
	"name" : "Dalacom",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 950.00,
	"usd" : 5.75,
	"profit" : 30,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "altel",
	"name" : "Dalacom",
	"number" : "3353",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 600.00,
	"usd" : 3.63,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "altel",
	"name" : "Dalacom",
	"number" : "3352",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 500.00,
	"usd" : 3.02,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "altel",
	"name" : "Dalacom",
	"number" : "3350",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 170.00,
	"usd" : 1.02,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Beeline",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 600.00,
	"usd" : 3.63,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Beeline",
	"number" : "3352",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 500.00,
	"usd" : 3.02,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Beeline",
	"number" : "8444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 375.00,
	"usd" : 2.27,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Beeline",
	"number" : "3350",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 170.00,
	"usd" : 1.02,
	"profit" : 30,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Beeline",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 75.00,
	"usd" : 0.45,
	"profit" : 25,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "kcell",
	"name" : "Kcell",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 700.00,
	"usd" : 4.23,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "kcell",
	"name" : "Kcell",
	"number" : "3353",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 600.00,
	"usd" : 3.63,
	"profit" : 25,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "kcell",
	"name" : "Kcell",
	"number" : "3352",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 500.00,
	"usd" : 3.02,
	"profit" : 25,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "kcell",
	"name" : "Kcell",
	"number" : "3350",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 170.00,
	"usd" : 1.02,
	"profit" : 25,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "kcell",
	"name" : "Kcell",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 75.00,
	"usd" : 0.45,
	"profit" : 25,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "mobiletelecomservice",
	"name" : "Mobile Telecom Service",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 700.00,
	"usd" : 4.23,
	"profit" : 40,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "mobiletelecomservice",
	"name" : "Mobile Telecom Service",
	"number" : "3353",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 600.00,
	"usd" : 3.63,
	"profit" : 35,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "mobiletelecomservice",
	"name" : "Mobile Telecom Service",
	"number" : "3352",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 500.00,
	"usd" : 3.02,
	"profit" : 35,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "mobiletelecomservice",
	"name" : "Mobile Telecom Service",
	"number" : "3350",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 170.00,
	"usd" : 1.02,
	"profit" : 35,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
},{
	"code" : "mobiletelecomservice",
	"name" : "Mobile Telecom Service",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 75.00,
	"usd" : 0.45,
	"profit" : 25,
	"vat" : 1,
	"currency" : "KZT",
	"special" : ""
}]
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "550",
	"rewrite" : "",
	"price" : 0.51,
	"usd" : 0.16,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "501",
	"rewrite" : "",
	"price" : 1.02,
	"usd" : 0.32,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "502",
	"rewrite" : "",
	"price" : 2.03,
	"usd" : 0.64,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "503",
	"rewrite" : "",
	"price" : 3.05,
	"usd" : 0.95,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "504",
	"rewrite" : "",
	"price" : 4.07,
	"usd" : 1.27,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 5.08,
	"usd" : 1.59,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "506",
	"rewrite" : "",
	"price" : 6.10,
	"usd" : 1.91,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "507",
	"rewrite" : "",
	"price" : 7.11,
	"usd" : 2.23,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "508",
	"rewrite" : "",
	"price" : 8.13,
	"usd" : 2.55,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "509",
	"rewrite" : "",
	"price" : 9.15,
	"usd" : 2.86,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 10.16,
	"usd" : 3.18,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "515",
	"rewrite" : "",
	"price" : 15.26,
	"usd" : 4.78,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LT",
	"country_name" : "Литва",
	"number" : "1394",
	"prefix" : "520",
	"rewrite" : "",
	"price" : 20.34,
	"usd" : 6.37,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "LTL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "502",
	"rewrite" : "",
	"price" : 0.25,
	"usd" : 0.39,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 0.50,
	"usd" : 0.76,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 1.54,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "515",
	"rewrite" : "",
	"price" : 1.50,
	"usd" : 2.3,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "520",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 3.06,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "525",
	"rewrite" : "",
	"price" : 2.50,
	"usd" : 3.83,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "530",
	"rewrite" : "",
	"price" : 3.00,
	"usd" : 4.59,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "540",
	"rewrite" : "",
	"price" : 4.00,
	"usd" : 6.13,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "LV",
	"country_name" : "Латвия",
	"number" : "1819",
	"prefix" : "550",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 7.65,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "LVL",
	"special" : "",
	"providers" : []
},{
	"country" : "NL",
	"country_name" : "Нидерланды",
	"number" : "4466",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 0.55,
	"usd" : 0.6,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "NL",
	"country_name" : "Нидерланды",
	"number" : "4466",
	"prefix" : "515",
	"rewrite" : "",
	"price" : 1.50,
	"usd" : 1.64,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "NL",
	"country_name" : "Нидерланды",
	"number" : "5030",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.50,
	"usd" : 1.64,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "NO",
	"country_name" : "Норвегия",
	"number" : "2227",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 3.93,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "NOK",
	"special" : "",
	"providers" : []
},{
	"country" : "NZ",
	"country_name" : "Новая Зеландия",
	"number" : "3903",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.50,
	"usd" : 2.92,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "NZD",
	"special" : "",
	"providers" : []
},{
	"country" : "PL",
	"country_name" : "Польша",
	"number" : "72240",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 0.66,
	"profit" : 25.00,
	"vat" : 0,
	"currency" : "PLN",
	"special" : "",
	"providers" : []
},{
	"country" : "PL",
	"country_name" : "Польша",
	"number" : "74240",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.00,
	"usd" : 1.32,
	"profit" : 27.00,
	"vat" : 0,
	"currency" : "PLN",
	"special" : "",
	"providers" : []
},{
	"country" : "PL",
	"country_name" : "Польша",
	"number" : "7643",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 6.00,
	"usd" : 1.98,
	"profit" : 27.00,
	"vat" : 0,
	"currency" : "PLN",
	"special" : "",
	"providers" : []
},{
	"country" : "PL",
	"country_name" : "Польша",
	"number" : "7943",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.00,
	"usd" : 2.97,
	"profit" : 30.00,
	"vat" : 0,
	"currency" : "PLN",
	"special" : "",
	"providers" : []
},{
	"country" : "PL",
	"country_name" : "Польша",
	"number" : "91909",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 19.00,
	"usd" : 6.27,
	"profit" : 35.00,
	"vat" : 0,
	"currency" : "PLN",
	"special" : "",
	"providers" : []
},{
	"country" : "PL",
	"country_name" : "Польша",
	"number" : "92505",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 25.00,
	"usd" : 8.25,
	"profit" : 35.00,
	"vat" : 0,
	"currency" : "PLN",
	"special" : "",
	"providers" : []
},{
	"country" : "PT",
	"country_name" : "Португалия",
	"number" : "68632",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.73,
	"usd" : 0.78,
	"profit" : 25.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "PT",
	"country_name" : "Португалия",
	"number" : "68634",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.01,
	"usd" : 1.06,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "PT",
	"country_name" : "Португалия",
	"number" : "68636",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.02,
	"usd" : 2.14,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "PT",
	"country_name" : "Португалия",
	"number" : "68638",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.03,
	"usd" : 4.29,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "RO",
	"country_name" : "Румыния",
	"number" : "1266",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.70,
	"usd" : 0.91,
	"profit" : 30.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "RO",
	"country_name" : "Румыния",
	"number" : "1380",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.50,
	"usd" : 1.95,
	"profit" : 35.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "RO",
	"country_name" : "Румыния",
	"number" : "1314",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 2.6,
	"profit" : 35.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "RO",
	"country_name" : "Румыния",
	"number" : "1263",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.13,
	"usd" : 3.9,
	"profit" : 35.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "RS",
	"country_name" : "Сербия",
	"number" : "1552",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.50,
	"usd" : 0.34,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "RSD",
	"special" : "+ price of the standard SMS",
	"providers" : []
},{
	"country" : "RS",
	"country_name" : "Сербия",
	"number" : "1553",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 128.00,
	"usd" : 1.35,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "RSD",
	"special" : "+ price of the standard SMS",
	"providers" : []
},{
	"country" : "RS",
	"country_name" : "Сербия",
	"number" : "1310",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 354.00,
	"usd" : 3.73,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "RSD",
	"special" : "+ price of the standard SMS",
	"providers" : []
},{
	"country" : "RU",
	"country_name" : "Россия",
	"special" : "",
	"providers" : [{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 254.24,
	"usd" : 7.94,
	"profit" : 60.69,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 144.07,
	"usd" : 4.50,
	"profit" : 60.8,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 84.75,
	"usd" : 2.64,
	"profit" : 61.31,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 59.32,
	"usd" : 1.85,
	"profit" : 61.58,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 37.29,
	"usd" : 1.16,
	"profit" : 56.68,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.66,
	"usd" : 0.92,
	"profit" : 57.4,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.95,
	"usd" : 0.52,
	"profit" : 57.71,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.48,
	"usd" : 0.26,
	"profit" : 53.96,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "beeline",
	"name" : "Билайн",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.24,
	"usd" : 0.13,
	"profit" : 42.17,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 44.33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 44.2,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 39.00,
	"usd" : 1.21,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 18.00,
	"usd" : 0.56,
	"profit" : 50.56,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 0.31,
	"profit" : 55,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "megafon",
	"name" : "МегаФон",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 0.15,
	"profit" : 37,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 258.30,
	"usd" : 8.07,
	"profit" : 56.08,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 172.20,
	"usd" : 5.38,
	"profit" : 54.81,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 85.81,
	"usd" : 2.68,
	"profit" : 58.4,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 54.53,
	"usd" : 1.70,
	"profit" : 58.08,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 37.31,
	"usd" : 1.16,
	"profit" : 53.97,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 28.41,
	"usd" : 0.88,
	"profit" : 56.95,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 17.22,
	"usd" : 0.53,
	"profit" : 50.17,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.61,
	"usd" : 0.26,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "mts",
	"name" : "МТС",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.31,
	"usd" : 0.13,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : "Стоимость доступа к услугам контент-провайдера устанавливается Вашим оператором. Подробную информацию можно узнать в разделе «Услуги по коротким номерам» на сайте www.mts.ru или обратившись в контактный центр по телефону 8 800 333 0890 (0890 для абонентов МТС)"
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 38,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 38,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.80,
	"usd" : 2.83,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.60,
	"usd" : 1.89,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 39.40,
	"usd" : 1.23,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 27.39,
	"usd" : 0.85,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 18.20,
	"usd" : 0.56,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.10,
	"usd" : 0.28,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "akos",
	"name" : "АКОС",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.50,
	"usd" : 0.14,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "altaysvyaz",
	"name" : "АлтайСвязь",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "altaysvyaz",
	"name" : "АлтайСвязь",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "altaysvyaz",
	"name" : "АлтайСвязь",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "altaysvyaz",
	"name" : "АлтайСвязь",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "altaysvyaz",
	"name" : "АлтайСвязь",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 35.00,
	"usd" : 1.09,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "altaysvyaz",
	"name" : "АлтайСвязь",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 287.00,
	"usd" : 8.96,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.00,
	"usd" : 5.28,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 89.00,
	"usd" : 2.78,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 59.00,
	"usd" : 1.84,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 39.00,
	"usd" : 1.21,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.00,
	"usd" : 0.90,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 19.00,
	"usd" : 0.59,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 0.31,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "baikalwestcom",
	"name" : "БайкалВестКом",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 0.15,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 144.07,
	"usd" : 4.50,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 88.98,
	"usd" : 2.78,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 59.32,
	"usd" : 1.85,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 38.14,
	"usd" : 1.19,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.66,
	"usd" : 0.92,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.95,
	"usd" : 0.52,
	"profit" : 44.97,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.47,
	"usd" : 0.26,
	"profit" : 45.06,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "bashsel",
	"name" : "BashSEL",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.66,
	"usd" : 0.14,
	"profit" : 45,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 39.00,
	"usd" : 1.21,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 18.00,
	"usd" : 0.56,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "3533",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.00,
	"usd" : 0.28,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "enisey",
	"name" : "Енисейтелеком",
	"number" : "2880",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.50,
	"usd" : 0.14,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "kodotel",
	"name" : "Кодотел",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 144.07,
	"usd" : 4.50,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "kodotel",
	"name" : "Кодотел",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 93.22,
	"usd" : 2.91,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "kodotel",
	"name" : "Кодотел",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 59.32,
	"usd" : 1.85,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "kodotel",
	"name" : "Кодотел",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 35.00,
	"usd" : 1.09,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "kodotel",
	"name" : "Кодотел",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.66,
	"usd" : 0.92,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "kodotel",
	"name" : "Кодотел",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.95,
	"usd" : 0.52,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 254.24,
	"usd" : 7.94,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 38.98,
	"usd" : 1.21,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 17.22,
	"usd" : 0.53,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "3533",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.00,
	"usd" : 0.28,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "motiv",
	"name" : "МОТИВ",
	"number" : "2880",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.50,
	"usd" : 0.14,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 254.24,
	"usd" : 7.94,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 84.36,
	"usd" : 2.63,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 56.24,
	"usd" : 1.75,
	"profit" : 32.77,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 36.56,
	"usd" : 1.14,
	"profit" : 32.6,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 27.84,
	"usd" : 0.87,
	"profit" : 32.54,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.68,
	"usd" : 0.52,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.43,
	"usd" : 0.26,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "nss",
	"name" : "НСС",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.22,
	"usd" : 0.13,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 260.00,
	"usd" : 8.12,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.00,
	"usd" : 5.28,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 86.71,
	"usd" : 2.70,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 58.00,
	"usd" : 1.81,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 37.70,
	"usd" : 1.17,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 28.71,
	"usd" : 0.89,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 17.40,
	"usd" : 0.54,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "3533",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.70,
	"usd" : 0.27,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "ntk",
	"name" : "НТК",
	"number" : "2880",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.35,
	"usd" : 0.13,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 35.00,
	"usd" : 1.09,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 17.22,
	"usd" : 0.53,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "3533",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.00,
	"usd" : 0.28,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "orenburggsm",
	"name" : "Оренбург-GSM",
	"number" : "2880",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.50,
	"usd" : 0.14,
	"profit" : 50,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 43,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 43,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 43,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 50.00,
	"usd" : 1.56,
	"profit" : 43,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 35.00,
	"usd" : 1.09,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 24.17,
	"usd" : 0.75,
	"profit" : 39,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 15.83,
	"usd" : 0.49,
	"profit" : 37,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.33,
	"usd" : 0.26,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "skylink",
	"name" : "SkyLink",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.17,
	"usd" : 0.13,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 296.91,
	"usd" : 9.27,
	"profit" : 28,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 28,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 89.83,
	"usd" : 2.80,
	"profit" : 27,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 55.08,
	"usd" : 1.72,
	"profit" : 27,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 50.85,
	"usd" : 1.58,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 27.12,
	"usd" : 0.84,
	"profit" : 25,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.94,
	"usd" : 0.52,
	"profit" : 25,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "3533",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.47,
	"usd" : 0.26,
	"profit" : 25,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts",
	"name" : "СМАРТС",
	"number" : "2880",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.24,
	"usd" : 0.13,
	"profit" : 20,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 81.36,
	"usd" : 2.54,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 55.09,
	"usd" : 1.72,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 38.98,
	"usd" : 1.21,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 22.12,
	"usd" : 0.69,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.95,
	"usd" : 0.52,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "3533",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.47,
	"usd" : 0.26,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_astragsm",
	"name" : "СМАРТС Астрахань-GSM",
	"number" : "2880",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.24,
	"usd" : 0.13,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 296.61,
	"usd" : 9.26,
	"profit" : 32,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 32,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 81.36,
	"usd" : 2.54,
	"profit" : 32,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 55.08,
	"usd" : 1.72,
	"profit" : 32,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 38.98,
	"usd" : 1.21,
	"profit" : 34.76,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 27.12,
	"usd" : 0.84,
	"profit" : 33.73,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.95,
	"usd" : 0.52,
	"profit" : 32.74,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.32,
	"usd" : 0.29,
	"profit" : 27.17,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_penzagsm",
	"name" : "СМАРТС Пенза-GSM",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.24,
	"usd" : 0.13,
	"profit" : 18.6,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 296.61,
	"usd" : 9.26,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.68,
	"usd" : 2.83,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.17,
	"usd" : 1.88,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 38.98,
	"usd" : 1.21,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.00,
	"usd" : 0.90,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 18.64,
	"usd" : 0.58,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.32,
	"usd" : 0.29,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_shupashkargsm",
	"name" : "СМАРТС Шупашкар-GSM",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.49,
	"usd" : 0.14,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 150.00,
	"usd" : 4.68,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 39.00,
	"usd" : 1.21,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 19.00,
	"usd" : 0.59,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 0.31,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_volgogradgsm",
	"name" : "СМАРТС Волгоград-GSM",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 0.15,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 296.61,
	"usd" : 9.26,
	"profit" : 32,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.49,
	"usd" : 5.29,
	"profit" : 32,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 89.83,
	"usd" : 2.80,
	"profit" : 27.15,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 58.47,
	"usd" : 1.82,
	"profit" : 33.44,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 38.14,
	"usd" : 1.19,
	"profit" : 35.64,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 28.81,
	"usd" : 0.90,
	"profit" : 38.52,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 18.64,
	"usd" : 0.58,
	"profit" : 35.8,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 10.17,
	"usd" : 0.31,
	"profit" : 31.98,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "smarts_yaroslavlgsm",
	"name" : "СМАРТС Ярославль-GSM",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 5.08,
	"usd" : 0.15,
	"profit" : 34.33,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tambovgsm",
	"name" : "Тамбов GSM",
	"number" : "4161",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 143.50,
	"usd" : 4.48,
	"profit" : 43,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tambovgsm",
	"name" : "Тамбов GSM",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 89.83,
	"usd" : 2.80,
	"profit" : 41,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tambovgsm",
	"name" : "Тамбов GSM",
	"number" : "4448",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.17,
	"usd" : 1.88,
	"profit" : 39,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tambovgsm",
	"name" : "Тамбов GSM",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 35.00,
	"usd" : 1.09,
	"profit" : 37,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tambovgsm",
	"name" : "Тамбов GSM",
	"number" : "4446",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.00,
	"usd" : 0.90,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tambovgsm",
	"name" : "Тамбов GSM",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 18.64,
	"usd" : 0.58,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 211.86,
	"usd" : 6.62,
	"profit" : 48.93,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.00,
	"usd" : 5.28,
	"profit" : 49.84,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 85.81,
	"usd" : 2.68,
	"profit" : 49.69,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 57.11,
	"usd" : 1.78,
	"profit" : 49.61,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 29.85,
	"usd" : 0.93,
	"profit" : 48.6,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 28.41,
	"usd" : 0.88,
	"profit" : 49.06,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "3833",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 17.22,
	"usd" : 0.53,
	"profit" : 49.49,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "3533",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.61,
	"usd" : 0.26,
	"profit" : 48.91,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "tele2",
	"name" : "Теле2",
	"number" : "2880",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.31,
	"usd" : 0.13,
	"profit" : 43.04,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 260.17,
	"usd" : 8.13,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 152.54,
	"usd" : 4.76,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.17,
	"usd" : 1.88,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 21.00,
	"usd" : 0.65,
	"profit" : 35,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 9.32,
	"usd" : 0.29,
	"profit" : 32.78,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uralsvyasinform",
	"name" : "Уралсвязьинформ",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 4.66,
	"usd" : 0.14,
	"profit" : 17.22,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uuss",
	"name" : "УУСС",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uuss",
	"name" : "УУСС",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.24,
	"usd" : 5.28,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uuss",
	"name" : "УУСС",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uuss",
	"name" : "УУСС",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uuss",
	"name" : "УУСС",
	"number" : "4447",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 35.00,
	"usd" : 1.09,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "uuss",
	"name" : "УУСС",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "volgatelecom",
	"name" : "ВолгаТелеком",
	"number" : "2474",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 300.00,
	"usd" : 9.37,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "volgatelecom",
	"name" : "ВолгаТелеком",
	"number" : "2476",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 169.24,
	"usd" : 5.28,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "volgatelecom",
	"name" : "ВолгаТелеком",
	"number" : "2322",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 90.00,
	"usd" : 2.81,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "volgatelecom",
	"name" : "ВолгаТелеком",
	"number" : "3933",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 60.00,
	"usd" : 1.87,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
},{
	"code" : "volgatelecom",
	"name" : "ВолгаТелеком",
	"number" : "2990",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 0.93,
	"profit" : 40,
	"vat" : 0,
	"currency" : "рубль",
	"special" : ""
}]
},{
	"country" : "SE",
	"country_name" : "Швеция",
	"number" : "72401",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 1.13,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "SEK",
	"special" : "",
	"providers" : []
},{
	"country" : "SE",
	"country_name" : "Швеция",
	"number" : "72702",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 3.4,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "SEK",
	"special" : "",
	"providers" : []
},{
	"country" : "SE",
	"country_name" : "Швеция",
	"number" : "72401",
	"prefix" : "530",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 3.4,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "SEK",
	"special" : "",
	"providers" : []
},{
	"country" : "SE",
	"country_name" : "Швеция",
	"number" : "72401",
	"prefix" : "550",
	"rewrite" : "",
	"price" : 50.00,
	"usd" : 5.67,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "SEK",
	"special" : "",
	"providers" : []
},{
	"country" : "SE",
	"country_name" : "Швеция",
	"number" : "72401",
	"prefix" : "580",
	"rewrite" : "",
	"price" : 80.00,
	"usd" : 9.07,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "SEK",
	"special" : "",
	"providers" : []
},{
	"country" : "SI",
	"country_name" : "Словения",
	"number" : "3838",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.49,
	"usd" : 2.7,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "SK",
	"country_name" : "Словакия",
	"number" : "6667",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 0.80,
	"usd" : 0.86,
	"profit" : 30.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "SK",
	"country_name" : "Словакия",
	"number" : "6674",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.59,
	"usd" : 1.73,
	"profit" : 30.00,
	"vat" : 0,
	"currency" : "EUR",
	"special" : "",
	"providers" : []
},{
	"country" : "UA",
	"country_name" : "Украина",
	"number" : "4443",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 0.1,
	"profit" : 10.00,
	"vat" : 1,
	"currency" : "UAH",
	"special" : "Дополнительно удерживается сбор в пенсионный фонд в размере 7,5% от стоимости услуги без учета НДС",
	"providers" : []
},{
	"country" : "UA",
	"country_name" : "Украина",
	"number" : "4444",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 2.00,
	"usd" : 0.21,
	"profit" : 20.00,
	"vat" : 1,
	"currency" : "UAH",
	"special" : "Дополнительно удерживается сбор в пенсионный фонд в размере 7,5% от стоимости услуги без учета НДС",
	"providers" : []
},{
	"country" : "UA",
	"country_name" : "Украина",
	"number" : "4445",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 3.80,
	"usd" : 0.4,
	"profit" : 20.00,
	"vat" : 1,
	"currency" : "UAH",
	"special" : "Дополнительно удерживается сбор в пенсионный фонд в размере 7,5% от стоимости услуги без учета НДС",
	"providers" : []
},{
	"country" : "UA",
	"country_name" : "Украина",
	"number" : "7054",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 8.00,
	"usd" : 0.84,
	"profit" : 37.00,
	"vat" : 1,
	"currency" : "UAH",
	"special" : "Дополнительно удерживается сбор в пенсионный фонд в размере 7,5% от стоимости услуги без учета НДС",
	"providers" : []
},{
	"country" : "UA",
	"country_name" : "Украина",
	"number" : "7074",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 12.00,
	"usd" : 1.26,
	"profit" : 37.00,
	"vat" : 1,
	"currency" : "UAH",
	"special" : "Дополнительно удерживается сбор в пенсионный фонд в размере 7,5% от стоимости услуги без учета НДС",
	"providers" : []
},{
	"country" : "UA",
	"country_name" : "Украина",
	"number" : "4449",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 16.00,
	"usd" : 1.68,
	"profit" : 37.00,
	"vat" : 1,
	"currency" : "UAH",
	"special" : "Дополнительно удерживается сбор в пенсионный фонд в размере 7,5% от стоимости услуги без учета НДС",
	"providers" : []
},{
	"country" : "UA",
	"country_name" : "Украина",
	"number" : "7094",
	"prefix" : "dam",
	"rewrite" : "",
	"price" : 30.00,
	"usd" : 3.15,
	"profit" : 37.00,
	"vat" : 1,
	"currency" : "UAH",
	"special" : "Дополнительно удерживается сбор в пенсионный фонд в размере 7,5% от стоимости услуги без учета НДС",
	"providers" : []
},{
	"country" : "UK",
	"country_name" : "Великобритания",
	"number" : "80079",
	"prefix" : "500",
	"rewrite" : "",
	"price" : 0.50,
	"usd" : 0.67,
	"profit" : 30.00,
	"vat" : 1,
	"currency" : "GBP",
	"special" : "Price £0.50 + normal network rates apply/ Need help? Mail to help@smscoin.com",
	"providers" : []
},{
	"country" : "UK",
	"country_name" : "Великобритания",
	"number" : "80079",
	"prefix" : "501",
	"rewrite" : "",
	"price" : 1.00,
	"usd" : 1.33,
	"profit" : 35.00,
	"vat" : 1,
	"currency" : "GBP",
	"special" : "Price £1.00 + normal network rates apply/ Need help? Mail to help@smscoin.com",
	"providers" : []
},{
	"country" : "UK",
	"country_name" : "Великобритания",
	"number" : "80079",
	"prefix" : "515",
	"rewrite" : "",
	"price" : 1.50,
	"usd" : 2,
	"profit" : 40.00,
	"vat" : 1,
	"currency" : "GBP",
	"special" : "Price £1.50 + normal network rates apply/ Need help? Mail to help@smscoin.com",
	"providers" : []
},{
	"country" : "UK",
	"country_name" : "Великобритания",
	"number" : "80079",
	"prefix" : "505",
	"rewrite" : "",
	"price" : 5.00,
	"usd" : 6.66,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "GBP",
	"special" : "Price £5.00 + normal network rates apply/ Need help? Mail to help@smscoin.com",
	"providers" : []
},{
	"country" : "UK",
	"country_name" : "Великобритания",
	"number" : "80079",
	"prefix" : "510",
	"rewrite" : "",
	"price" : 10.00,
	"usd" : 13.3,
	"profit" : 45.00,
	"vat" : 1,
	"currency" : "GBP",
	"special" : "Price £10.00 + normal network rates apply/ Need help? Mail to help@smscoin.com",
	"providers" : []
}
]